pipeline {
    agent any

    stages {
        stage('verify tooling') {
            steps {
                sh '''
            docker version
            docker info
            docker compose version
            ls
            '''
            }
        }

        // stage('Clone repo') {
        //     steps {
        //         git url: 'https://github.com/dmitrymailk/django_docker_compose.git'
        //     }
        // }

        // stage('Build') {
        //     steps {
        //         dir('minimal_app') {
        //             sh 'docker-compose up -d --build'
        //             sh 'docker-compose ps'
        //         }
        //     }
        // }
        // stage('Test') {
        //     steps {
        //         echo 'Testing..'
        //     }
        // }
        // stage('Deploy') {
        //     steps {
        //         echo 'Deploying....'
        //     }
        // }
    }

    // post {
    //     always {
    //         dir('minimal_app') {
    //             sh 'docker-compose down --remove-orphans -v'
    //             sh 'docker-compose ps'
    //         }
    //     }
    // }
}
