# Generated by Django 4.0.2 on 2022-09-02 21:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('views_counter', '0002_rename_count_counter_my_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='current_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
