# Generated by Django 4.0.2 on 2022-09-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('views_counter', '0003_counter_current_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='current_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
